[package]
name = "test"
version = "2.0.0-beta.2"
authors = ["Tim Hall <tim.hall.engr@gmail.com> (https://github.com/timhall)"]

[src]
TestSuite = "src/TestSuite.cls"
TestCase = "src/TestCase.cls"
ImmediateReporter = "src/ImmediateReporter.cls"
FileReporter = "src/FileReporter.cls"

[dependencies]
dictionary = "^1"

[dev-src]
Tests = "tests/Tests.bas"
Tests_TestCase = "tests/Tests_TestCase.bas"
Tests_TestSuite = "tests/Tests_TestSuite.bas"
Test_Fixture = "tests/Test_Fixture.cls"
